apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: nexus
spec:
  clusterIP: 10.0.167.96
  selector:
    app: nexus
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP #changed from Loadbalancer for internal only