apiVersion: v1
kind: Service
metadata:
    name: bazelremote-svc
    namespace: bazelremote-ns # Ensure this matches the namespace name
spec:
    selector:
      app.kubernetes.io/name: bazelremote # This matches the labels in your bazelremote Deployment
    ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
      name: grpc
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http-default
    type: ClusterIP # For internal cluster access